### ISSUE TITLE
Please be more correct

### ISSUE THREAD

**Issue by andischan** [osmlab/labuildings#117]
> Buildings data will encourage more map edits. Once buildings are in the map, people will be able to orient themselves to the shapes, making it easier to add more data, like names or businesses.

This is wrong. It maybe encourage casual editors, but it prevent the developement of an experienced (=JOSM using) mapper community.

In the US there was only 3 % growth in six years due to TIGER import. The mapping detail in the United States outside the big cities is very bad. Oklahoma is mapped worse than even Russia!

**Comment by almccon** [comment]
@andischan I understand your point of view, but this is a long-standing argument within the OSM community (whether imports help community or hurt it) and there is no convincing evidence either way. It is impossible to prove that the TIGER import hindered the growth of the US community, or whether it made no difference at all.

In any case, the LA Buildings project has done _everything_ it can to make sure that this import process helps build community. We have followed the best practices for imports, and we've studied previous imports and learned all the lessons we can. 

Please watch the video from Omar and Jon to see how much consideration we put into this project: http://stateofthemap.us/2016/lets-get-la-on-the-map/

Since there is nothing actionable in this issue, and this is a discussion that has already happened many times before, I'm going to close this issue.
