### ISSUE TITLE
Modify convert.py to translate assessor data into OSM tags

### ISSUE THREAD

**Issue by almccon** [osmlab/labuildings#14]
See #3 for more info about assessor data.

`convert.py` already combines addresses with buildings using the AIN field. We plan to use the AIN field to join the assessor data too.

**Comment by jschleuss** [comment]
Just joined the assessor data straight to the building shapefile. Rehosted at [latimes](https://github.com/osmlab/labuildings/blob/master/Makefile#L9).

**Comment by almccon** [comment]
Great! I assume we still need to figure out how to translate those assessor fields into OSM tags. Maybe that discussion should go in #3, or maybe it should happen in this issue?

**Comment by jschleuss** [comment]
@cityhubla and I did some of that work already. I think the decision was spelled out in the [readme](https://github.com/osmlab/labuildings#building-attributes). I modified [convert.py](building) to handle those. Though, it doesn't line up perfectly with how OSM does things. For instance, OSM community would prefer "building=apartments" instead of "building=Residential"

**Comment by almccon** [comment]
Yes, we should re-run the sample data. In #21 and few other issues, @maning is looking at my sample .osm files, but now they're obsolete since you've incorporated the assessor data.

Unfortunately I don't have time to regenerate those files myself... If anyone else gets a chance to regenerate the samples, please replace the https://github.com/osmlab/labuildings/blob/master/venice_osm.zip file, or change the [readme](https://github.com/osmlab/labuildings/blob/master/README.md) to link to something else.

**Comment by maning** [comment]
I regenerated a new sample data [here](https://github.com/maning/labuildings/blob/building_types/sample_osm.zip) based of the joined dataset from assesor data.  I also fixed a few lines in convert.py to [handle NULL values in some fields](https://github.com/maning/labuildings/commit/84a2b5963470aed1b743017cce92eb1d30169186).

We also need to agree on how to convert the `SpecificUseType` and `SpecificUseDetail1` into proper OSM tags.  I can do the attribute matching.  Should I, **convert to OSM tags into the source shapefile** or **should we create another script** to clean this up (former should easiest for me)?

**Comment by jschleuss** [comment]
@maning how would you go about converting the OSM tags in the source shapefile? I'm guessing some scripting logic?

**Comment by planemad** [comment]
Going through the [attributes spreadsheet](https://docs.google.com/spreadsheets/d/1A3whba04_-3K0z77nGHYavIwYpWjnyAaInwWie3HSVA/edit#gid=752018497), an important question for me is if it is sensible to import so much street detail from 10 years ago without a `name=*` tag? it would be a massive task for mappers to verify and clean this data once it is imported into OSM.

The `SpecificUseType` which makes sense for me to import are those that are verifiable from imagery to some extent:
- parking
- fuel station
- school
- college
- hospital
- golf course

Otherwise we should just stick to importing the `building=*` value best we can and punt on others till we can get a more updated dataset rather than a huge conflation/verification headache later on.

@jschleuss @almccon @talllguy @maning

**Comment by maning** [comment]
@jschleuss, per conversation with my team, it make sense to process the tag through a "sanitizer" script before writing the xml file.  Depending on the implementation, it can either be separate script where we feed a csv of OSM tags based on the spreadsheet or expand convert.py to do this similar to what it does for addresses.

Before implementation, we need to agree first if its worth the effort to do this considering the above comment by @planemad 

cc/ @almccon @cityhubla @batpad

**Comment by jschleuss** [comment]
@planemad @maning I'm not sure what data is 10 years old. Do you mean the building shapefile and AINs from the 2008 file released in 2009? The Assessor just recently released their 2015 roll information and that's what we've attached to the building file. So the data attributes should be pretty fresh. I don't see a compelling reason to drop it, but would see the need to write the sanitizing script to better match the OSM tags.

**Comment by planemad** [comment]
@jschleuss thanks for clarifying, I missed the fact that the assessor data was released in 2015, so that makes more sense to import.

How will we handle amenity/shop tags on building parts? https://github.com/osmlab/labuildings/issues/19#issuecomment-171596408

**Comment by maning** [comment]
related to: https://github.com/osmlab/labuildings/issues/3

**Comment by maning** [comment]
Closing.
