### ISSUE TITLE
Fields to be imported?

### ISSUE THREAD

**Issue by bcamper** [osmlab/labuildings#3]
Hi, could you let us know which of the fields in the original dataset you plan to import, and what the corresponding proposed OSM tags will be? Apologies if I missed this somewhere!

**Comment by cityhubla** [comment]
Regarding the Unique building IDs, the NYC import has them included, it may be best to add them as well. I could contact LA county to see if the 2014 LARIAC bldg outlines (non-public) are completely new IDs and different from the 2008 public set we're using. I'm anticipating the new set to have outlines with recently constructed buildings replacing existing ones, we could then automate this by removing those IDs that are no longer there with the new ones. I'm also wondering if there is a way to retag the removed outlines for archiving.

**Comment by cityhubla** [comment]
Also, the data behind the elevations are sketchy at best, the numbers are off at some buildings, this 3D demo I made of Hollywood <a href="http://www.cityhub.la/maptimela/test_threeqgis/test_1.html">Test ThreejsQGIS demo</a> shows the discrepancy. At the office I work at, we use the outlines to build our 3D contextual site models for conceptual architectural work. I usually have to recenter the object axes to then intersect with the terrain in software like Rhino3d or Sketchup.

**Comment by cityhubla** [comment]
It may take quite a bit of time to average them out, if we script something where it takes a feature and determines whether it's ELEV is within the average of the closest surrounding buildings.

**Comment by cityhubla** [comment]
We may have some luck with the incoming LA County Open Data Initiative, <a href="http://assessor.lacounty.gov/open-data-initiative/">Open Data Initiative</a> it seems the county assessor is actually going to  release the roll data for each parcel for free, (more up to date than what I found from UCLA). Would this help in the code development? One attribute that would be very beneficial is the "building type" the roll data identifies the building as either a single family home, commercial, mixed, civic, school, church, etc. The text says that the data portal would be accessible on or after March 30th.

**Comment by cityhubla** [comment]
Here's an description on the use codes in that dataset
![usecodes](https://cloud.githubusercontent.com/assets/6407796/6820058/4c539048-d288-11e4-95c9-b2033579a6b2.jpg)

**Comment by almccon** [comment]
Oh, that does look quite interesting! I'd love to be able to use `building=apartments` and `building=house` instead of just `building=yes`. 

http://wiki.openstreetmap.org/wiki/Tag:building%3Dhouse
http://wiki.openstreetmap.org/wiki/Tag:building%3Dapartments

In fact, many of those, like churches, schools, hospitals, could also be captured.

And @lyzidiamond and @joeyklee would love `Single family residence with pool`, even though we probably can't use that one meaningfully for the import.

**Comment by almccon** [comment]
http://wiki.openstreetmap.org/wiki/Tag:building%3Dgarage would also be great for all those garages behind single-family homes

**Comment by almccon** [comment]
Just had a thought: does the assessor data contain information about the number of floors in the building? If so, we can populate the [building:levels](http://wiki.openstreetmap.org/wiki/Key:building:levels) tag as well as the [height](http://wiki.openstreetmap.org/wiki/Key:height) which comes from the building footprint data.

**Comment by joeyklee** [comment]
For the case of LA, I don't think it is included (http://assessor.lacounty.gov/local-roll/), but I do think the "building:levels " tag would be a worth adding since it could be something derived via geotagged photos or google streetview imagery :) 

In cases like the Chicago building footprint data, they include building:levels for some of their buildings.

**Comment by almccon** [comment]
Bummer. If it's not in the assessor data then we can't include it in the import. But there's nothing stopping people from adding it later based on ground-level imagery or surveying on-the-ground. 

We can't use Google Street View for OSM mapping because of the license, but we _can_ use Mapillary where available: http://www.mapillary.com/map/im/2FuBwfL320GgjY5amgiCgw/photo

**Comment by joeyklee** [comment]
That is no bueno. And definitely good point about the licensing. Always something to keep in mind ;)

**Comment by cityhubla** [comment]
@jschleuss and I made this google spreadsheet to figure out the fields and their OSM tag

[Attributes to be imported, Google Spreadsheets](https://docs.google.com/spreadsheets/d/1A3whba04_-3K0z77nGHYavIwYpWjnyAaInwWie3HSVA/edit#gid=0)

There are two distinct uses that the [2014 Assessor's data](https://data.lacounty.gov/Parcel-/Assessor-Parcels-Data-2014/kbm6-eaaf) (also referred to issue #15) has:
*  GeneralUseType (General Use of the building, ie, Residential, Commercial, Industrial, Institutional)
*  SpecificUseType (More specific use of the building, ie, Single Family Residence, Church, Bowling Alley, Golf Course)
*  SpecificUseDetail1 (Additional detail to building, ie Dance Hall, Supermarket)

Jon and I propose that the these tags could be attached during the import.

*  GeneralUseType || building tag
*  SpecificUseType || building:use tag
*  SpecificUseDetail1 || amenity tag

For example if a building is detached single family residence its tag is as follows
*  building=residential
*  building:use=Single Family Residence

OSM's [taginfo](http://taginfo.openstreetmap.org/keys/building#values) shows residential as a general tag, we could consider the building tag as general. We think there should be a general tag for general designations like residential, commercial, industrial, with a subtag like building:use as whether a residential is either single family, duplex, triplex condominum.

The data in the assessor's is fine grain, we're open to tagging them differently. Thoughts?

**Comment by cityhubla** [comment]
@joeyklee @almccon,

The SpecificUseDetail2 of the data, [2014 Assesor's data](https://data.lacounty.gov/Parcel-/Assessor-Parcels-Data-2014/kbm6-eaaf) has these values 
*  14 to 20 Stories
*  6 to 13 Stories
*  Five Stories
*  Four Stories
*  One Story
*  Over 20 Stories
*  Three Stories
*  Two Stories

We could update the script to add these to the [building:levels] tag(http://wiki.openstreetmap.org/wiki/Key:building:levels)

**Comment by joeyklee** [comment]
@cityhubla Nice find! I'm sorry I missed that. It's been awhile since I revisited the data. Better two brains than one!

**Comment by cityhubla** [comment]
The only issue is that this category has values like Modular, pool, vacant land, fast food etc. It would have to be sorted during scripting. Those identified as 14-20 or 6-13 would need to be omitted as the tag is number based, right?

**Comment by cityhubla** [comment]
Here is a breakdown of all the unique values in the use categories, [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1A3whba04_-3K0z77nGHYavIwYpWjnyAaInwWie3HSVA/edit#gid=1971401153)

**Comment by cityhubla** [comment]
I'm figuring out the markdown syntax for adding tables to the readme, We could transition the gdoc to the readme or create a wiki to simplify what attributes we're importing

**Comment by almccon** [comment]
This is great! I think we can add these tables to the README in Markdown, or else put them in the wiki on osm.org. Eventually we'll have to document everything on OSM's wiki anyway. But we shouldn't use the github wiki, since that will just confuse things.

**Comment by jschleuss** [comment]
@cityhubla okay. I added the 2015 Assessor data to that [spreadsheet](https://docs.google.com/spreadsheets/d/1A3whba04_-3K0z77nGHYavIwYpWjnyAaInwWie3HSVA/edit?usp=sharing). I also started thinking about the OSM tags, starting with our thoughts above. I think we could work with OSM's tags a bit with building=house or building=school. And then go generic when we don't have more information.

We could augment the script to look for both values before making a "decision" on the tags to add. Maybe we do something similar for SpecificUseType1 and 2?

**Comment by jschleuss** [comment]
@almccon you know the [assessor's data](https://data.lacounty.gov/Parcel-/Assessor-Parcels-Data-2015/5xcg-yews) also has address fields, right? But we're opting for the address points because some buildings will have multiple addresses? Is that right?

**Comment by almccon** [comment]
No, I did not know that the assessor's data has addresses. But you're correct, if the assessor only has one address per parcel then the address points will be preferable.

**Comment by cityhubla** [comment]
Table has been added to the readme, I'll update the osm wiki. From the looks of it, and what Jon and I talked last Sunday, our import will be really comprehensive. Lots of great data.

**Comment by cityhubla** [comment]
If anyone has time, the assessor's data has values in the USE columns that could be sorted into specific OSM tags, like the `building:levels` tag, here is a [gdoc of values](https://docs.google.com/spreadsheets/d/1A3whba04_-3K0z77nGHYavIwYpWjnyAaInwWie3HSVA/edit?usp=sharing) to see if there are some that could be sorted otherwise the script would be tagged with `building:use`

**Comment by planemad** [comment]
Just went through the discussions and it looks like we can categorize the fields into two parts:
- Building attributes specific to the footprint (area): If the building has been reconstructed since 2008, these are useless
- Address attributes specific to the geographic location (point): These are usually valuable even if the building footprint has changed

Per this trial https://github.com/osmlab/labuildings/issues/18#issuecomment-167976124 I did notice that around 1 in 20 buildings had changed and were not good to be imported. If we tie in the address fields to the building footprints while importing, we will have to discard both the footprints and address together, but ideally we would want to import the address as a point property or add it to a newer footprint if possible.

How about we split the dataset into polygons with just the footprint and building attributes, and a point dataset of address attributes extracted from building centroids?

This will allow us to better fill data gaps in OSM rather than trying to throw all the data in at once:
1. Import only the footprints and building attribute that match with imagery
2. Update any existing OSM footprint geometry if needed
3. Conflate the address points to the latest building footprint on OSM if they overlap, manually inspect addresses which did not overlap

**Comment by maning** [comment]
I took a stab at reviewing the [Assessor categories](https://github.com/osmlab/labuildings/issues/3#issuecomment-134314783).  I think it contains a lot of information that can fine tune the `building` tag other than what is in the `GeneralUse` fields.  For one, OSM doesn't have `Institutional` and `Miscellaneous`.  

What I did was first compare the `GeneralUse` and `SpecificUse` and [categorized](https://docs.google.com/spreadsheets/d/1A3whba04_-3K0z77nGHYavIwYpWjnyAaInwWie3HSVA/edit#gid=1310416570) according to what tag exist in OSM according to [Taginfo](https://taginfo.openstreetmap.org/keys/building#values).  Then, I compared `SpecificUse` and `Specific_1` and [categorized](https://docs.google.com/spreadsheets/d/1A3whba04_-3K0z77nGHYavIwYpWjnyAaInwWie3HSVA/edit#gid=198935352) anything that were left out.

In most cases, we will override the `GeneralUse` in favor of `SpecificUse`.  For example,
A feature which has  `GeneralUse = Commercial`; `SpecificUse=Department Store` will be
`building=department_store`.  Or `GeneralUse=Recreational`; `SpecificUse=Athletic and Amusement Facility`; `Specific_1 = Dance Hall` will be  `building=recreational`; `building:use=dance_hall`. 

Tags I'm seeing we can include are building, building:use and building:levels.  I don't think adding the the `amenity` and `shop` tags is appropriate since it will be included in the [smaller buildings within the propery/parcel](https://github.com/osmlab/labuildings/issues/19#issuecomment-171301786).

**Pros** - we adopt common OSM convention on tagging buildings. We transalte as much info as possible from the source.
**Cons** - we lose that actual source attributes from the Assesor database.

For cleaning this, we will modify convert.py.  Please go over the [spreadsheet](https://docs.google.com/spreadsheets/d/1A3whba04_-3K0z77nGHYavIwYpWjnyAaInwWie3HSVA/edit#gid=1310416570) and review.

**Comment by maning** [comment]
PR for review here. https://github.com/osmlab/labuildings/pull/28

**Comment by maning** [comment]
There cases where a different building category from Assessor data is assigned to two parts of a building. 

![screen shot 2016-02-09 at 14 54 06](https://cloud.githubusercontent.com/assets/353700/12913040/66b8c5e0-cf42-11e5-87d7-db039777ae35.png)

**Comment by talllguy** [comment]
@maning in https://github.com/osmlab/labuildings/issues/3#issuecomment-181793071 what are the two tags?

**Comment by maning** [comment]
@talllguy, the yellow = residential, purple = industrial.  The area northwest is an industrial complex.

**Comment by talllguy** [comment]
@maning interesting. I suspect a zoning boundary caused this. Having worked for a County gov't GIS team, I wouldn't be surprised if such a method was used to tag building uses by an assessor. You might try loading the zoning boundary if you can find it on LA county's open data site to compare.

My prediction is that the zoning line will transect the building right where the split is, because zoning lines were historically mapped on small scale maps by hand, long before GIS was around. Then when GIS came around, GIS analysts were forced to digitize the zoning lines exactly where they were on the map, because changing them at all requires a law change. I digress. Check that zoning line and then if it is the culprit, you might just want to us an algorithm to decide to merge the larger piece, or ignore these zoning inferred tagging.

Also, regarding *institutional*, my county used that as well. In my import, I believe I changed them all to building=yes, because there was no positive way to say what they translated to. Typically they're school, college or government though.

**Comment by maning** [comment]
>  suspect a zoning boundary caused this. Having worked for a County gov't GIS team, I wouldn't be surprised if such a method was used to tag building uses by an assessor. You might try loading the zoning boundary if you can find it on LA county's open data site to compare.

You are correct we used LA County's Assessor data by joining the  building shapefile and assessor csv using `AIN` as the join field attribute. 
 
> Also, regarding institutional, my county used that as well. In my import, I believe I changed them all to building=yes, because there was no positive way to say what they translated to. Typically they're school, college or government though.

You are correct again, `building=institutional` is not an OSM tag.  For this, we created a lookup table by using secondary use type of the building.  For example, in the assessor data, there a `generaluse=building`, `specificuse=school` we used the tag `building=school` for such cases. See:  https://github.com/osmlab/labuildings/tree/master/mappings_csv

**Comment by maning** [comment]
Closing.
For  building parts where Assessor data assigned different classification, importer should do manual merge.
