### ISSUE TITLE
Trial run results

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#43]
Today, a few of us tested the import process.  Note: we didn't import anything in the main OSM db.  For this test we uploaded data in the OSm dev server.  See edits here: http://master.apis.dev.openstreetmap.org/history#map=14/34.0220/-118.4653

Some notes:

- The download data should only show after you click start mapping to avoid mappers working on a task without locking it<br> <img width="409" alt="screenshot 2016-02-19 11 57 29" src="https://cloud.githubusercontent.com/assets/126868/13168211/67e822f6-d700-11e5-94ab-59ac8cdd6cb4.png">

- Is it better to just have one button to download both OSM data and import data into separate JOSM layers at once? What is the advantage of having two buttons that we click one after the other?

- We need an **object conflation tool:**
 - When merging two objects, the mapper only needs to select which object's properties to inherit. Currently we need to select this for each individual tag and is not practical.<br>
<img width="730" alt="screenshot 2016-02-19 12 35 31" src="https://cloud.githubusercontent.com/assets/126868/13168720/4c591dce-d705-11e5-9a71-e4f780b562c9.png">
 * Like **replacing geometry we need a replace tags function to update the tags from another object and delete the unused geometry.** Current workflow is, selecting import geometry, copy tags, select target geometry, paste tags, select import geometry and delete it.
* **Do we join building parts**?  If yes, we should use the attributes of the bigger building, this needs proper joining of attribute tool as explained above.
* **For areas with existing buildings in OSM, we need to properly visualize the difference between the imported data and existing data**.  Suggestion is to **prepare a map paint style  (mapCSS) for JOSM**. 
* Should we import the  `building:levels=<4`?
* **If no building exist in the imagery, do we delete**?  The imagery is 2014. The building data is 2008 and 2014.  It is possible that the data is outdated.  Conversely, **should we trace building if its visible in the imagery and missing in the import data?**
* Importing guide needs more explanation on **how to do comparison from existing data and conflation.**
* The TM task boundary was based on census blocks, this makes it difficult to visualize the edges the task a user is working on.  Suggestion is to create a **background image overlay to show the boundaries of the task.**
* Some buildings have an offset from the imagery, should we **move the building polygon?**

**Comment by maning** [comment]
> The download data should only show after you click start mapping to avoid mappers working on a task without locking it
Fixed.

**Comment by maning** [comment]
> Suggestion is to create a background image overlay to show the boundaries of the task.

![screen shot 2016-03-10 at 19 13 58](https://cloud.githubusercontent.com/assets/353700/13671194/76b09f58-e6f4-11e5-8f8f-88e0ec8f1206.png)

We created an image overlay to visualize census blocks borders.  This will be loaded automatically within the tasking manager.

**Comment by jschleuss** [comment]
@maning the outline overlay sounds like a good idea to me. But I'll only work on purple blocks (just kidding).

> We need an object conflation tool:

What would that tool look like? I'm thinking if a merge is needed we could ask the user to delete the lacounty-bld_id tag. The AIN will likely be the same because it refers to the entire property. Would that work?

> Do we join building parts? If yes, we should use the attributes of the bigger building, this needs proper joining of attribute tool as explained above.

My initial thought is no. Because you might have medium density commercial buildings right next to each other that should be considered separate. However, small attachments to the backs of houses could probably be merged. So, I'm thinking we should't unless it's very clear that the building part belongs to that building and not a neighboring building that just touches that first one.

> For areas with existing buildings in OSM, we need to properly visualize the difference between the imported data and existing data. Suggestion is to prepare a map paint style (mapCSS) for JOSM.

I think this is a good idea. 

> Should we import the building:levels=<4?

I think we should use it. It'll throw errors, but I think it's worthwhile to keep this.

> If no building exist in the imagery, do we delete? The imagery is 2014. The building data is 2008 and 2014. It is possible that the data is outdated. Conversely, should we trace building if its visible in the imagery and missing in the import data?

Yes, if the building isn't in the imagery we should delete it. And yes, we should trace buildings in the imagery that aren't in the data. That also means deleting buildings that have replaced what's in the imagery vs. what's in the data. There are a few examples of that in the sample data. 
![screen shot 2016-03-10 at 9 00 27 am](https://cloud.githubusercontent.com/assets/695934/13677376/97d9ecee-e69e-11e5-99dc-00d87980ec26.png)

> Some buildings have an offset from the imagery, should we move the building polygon?


Unless it's a very large offset, I'd suggest sticking with the data. The data came from flying planes with lasers above the county, so it should probably be the higher authority on specific details.

**Comment by maning** [comment]
Immediate tasks hit.  No pending actionable tasks. Closing.
