### ISSUE TITLE
Task manager doesn't tally contributions properly

### ISSUE THREAD

**Issue by dkogan** [osmlab/labuildings#69]
Hi. Currently the task manager claims that I have imported 18 sets of data. This is incorrect: I only imported 16. When my browser queries the server, it says I have imported these:

```

618
393
398
443
536
352
340
538
538
551
550
546
549
217
218
538
463
573
```

Note that 538 appears 3 times and is the cause of the discrepancy.

**Comment by maning** [comment]
@dkogan Can you share how were you able to query this? Looking at the tasks activity log:
http://labuildingsimport.com/project/2#task/538 
It seems you've marked 538 as done 3 times.

**Comment by dkogan** [comment]
Maning Sambale <notifications@github.com> writes:

> @dkogan Can you share how were you able to query this?

I loaded the Stats page while running tcpdump. We're not encrypting
anything, so nothing else was required. It would be nice if this
information was exposed on the page somewhere.


> Looking at the tasks activity log:
> http://labuildingsimport.com/project/2#task/538 It seems you've marked
> 538 as done 3 times.

OK, so that's clearly the source of the bug.

**Comment by maning** [comment]
![screen shot 2016-04-06 at 18 05 21](https://cloud.githubusercontent.com/assets/353700/14316706/2b7f6fc6-fc22-11e5-8700-09aab7482068.png)

@dkogan, I'm not seeing any clear actions on this the Tasking Manager UI,  implies that a user contributed on and not necessarily completed the project.

**Comment by dkogan** [comment]
Maning Sambale <notifications@github.com> writes:

> @dkogan, I'm not seeing any clear actions on this the Tasking Manager
> UI, implies that a user contributed on and not necessarily completed
> the project.

I'm not sure what you mean. This is a bug in whatever chunk of software
is doing this counting. Do we have access to the sources? Can we see how
the counting is done?

**Comment by cityhubla** [comment]
@dkogan, the source files are at the [HOTOSM github repo](https://github.com/hotosm/osm-tasking-manager2).

**Comment by dkogan** [comment]
Omar Ureta <notifications@github.com> writes:

> @dkogan, the source files are at the [HOTOSM github
> repo](https://github.com/hotosm/osm-tasking-manager2).

OK. I'm going to ask for more detail. Where/how is the server hosted?
It's running a different copy of those sources. Are there modifications?

To be clear, if whoever runs the server wants to just fix it themselves,
that's perfectly fine by me. Otherwise, I can look at it, if given the
necessary access.

**Comment by dkogan** [comment]
Omar Ureta <notifications@github.com> writes:

> @dkogan, the source files are at the [HOTOSM github
> repo](https://github.com/hotosm/osm-tasking-manager2).

Potential fix in https://github.com/dkogan/osm-tasking-manager2

Untested.

**Comment by batpad** [comment]
Hi @dkogan -

I've been one of the folks managing the hosting for this instance of the Tasking Manager - we are using the HOT Tasking Manager code-base https://github.com/hotosm/osm-tasking-manager2 with a few minor changes to better support the import process.

You can see the exact code that is being run on the server in this branch: https://github.com/osm-in/osm-tasking-manager2/tree/labuildings-import (am fairly certain our custom modifications here are not related to the bug that you are seeing).

What I would suggest is:

 - Create an issue in the main tasking manager repository: https://github.com/hotosm/osm-tasking-manager2/issues
 - Make a Pull Request with your fix to the Tasking Manager repository referencing the issue.

When the change gets reviewed and merged upstream, am happy to merge in and deploy the changes to our custom instance. This seems like a good fix, so please let me know if I can help in any way.

Just also FYI, we are working on getting our custom changes merged upstream so that we will not need to maintain this fork much longer. You can track progress of that Pull Request here: https://github.com/hotosm/osm-tasking-manager2/pull/767

Thanks much for the report and potential fix - hopefully you can follow up with upstream and I can merge in the changes. Please let me know if you have any additional questions about our setup and if I can help in any way.

**Comment by dkogan** [comment]
I reported the issue upstream. Thanks for pointing me there.

**Comment by maning** [comment]
@dkogan Thanks for the PR upstream, closing this issue.
